SP_NAME: iac-deployer
ROLES:
  - Contributor
  - User Access Administrator
  - Key Vault Secrets Officer
SUBSCRIPTION: 95273533-6484-4c3f-b494-a7db2c17d6fd
TENANT_ID: b4fb25b9-fc3f-4c31-bee7-f45bccc198d2
SECRET_NAME: iac-deploy-secret
EXPIRY_YEARS: 2
EXPIRY_MONTHS: 6
EXPIRY_DAYS: 19